import = [ "/home/mtbossa/.config/alacritty/themes/iterm.toml" ]
draw_bold_text_with_bright_colors = true

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
opacity = 0.9

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"

[[key_bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"
